name: Cypress Tests

on:
  push:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6